#!/bin/bash
cd $HOME
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;33mMbs PESSOAL!\033[0m"

echo -e "\033[0m\033[01;37m(2) \033[01;33mMBs Com Número\033[0m"

echo -e "\033[0m\033[01;37m(3) \033[01;33mTOKEN PESSOAL\033[0m"

echo -e "\033[0m\033[01;37m(4) \033[01;33mTOKEN Com Número\033[0m"

echo -e "\033[0m\033[01;37m(5) \033[01;33m outros\033[0m"

echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo " "
echo -e "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "
read OPTION

case $OPTION in
        (1) 
                curl -sO https://raw.githubusercontent.com/madson2391/MB-TESTE/main/MBs && chmod 777 MBs && ./MBs
                        ;;
                                (2) 
                                        curl -sO https://raw.githubusercontent.com/madson2391/MB-TESTE/main/MBsComNumero && chmod 777 MBsComNumero && ./MBsComNumero
                                                ;;
                                                        (3) 
                curl -sO https://raw.githubusercontent.com/madson2391/MB-TESTE/main/Token && chmod 777 Token && ./Token
                        ;;
                                (4) 
                                        curl -sO https://raw.githubusercontent.com/madson2391/MB-TESTE/main/TokenComNumero && chmod 777 TokenComNumero && ./TokenComNumero
                                        ;;
                                                        (5)
                                                                curl -sO https://raw.githubusercontent.com/fabricio94b/PacoteFree/main/mbsfree2 && chmod 777 mbsfree2 && ./mbsfree2                                                
                ;;
                                                                                        (*) echo -e "\033[1;31mOpção invalida\033[1;37m"
   esac
