#!/bin/bash
clear
echo -e "\033[01;32m Instalando ferramentas necessarias!\033[01;37m"
sleep 1
pkg install pv -y -qq --silent
sleep 1
pkg install cmatrix -y -qq --silent
sleep 1
pkg install jq -y -qq --silent
sleep 1
pkg install git -y -qq --silent
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m            • PACOTE FREE •             \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "    \033[0m\033[01;37m• \033[01;33mToken padrão \033[0m\033[01;37m•\033[0m"
echo -e "\033[01;32m Aprovado \033[0m\033[0m\033[01;37m= Recebera os MB"
echo -e "\033[01;31m Reprovado \033[0m\033[0m\033[01;37m= Não recebera os MB"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
sleep 1
echo -e "\033[01;33m Total de Tokens:\033[0m \033[0m\033[01;37m18 "
echo ""
echo -e "\033[01;32m Cole seu Token:\033[01;37m"
read TOKEN
NUMERO="5593991113234";
VEZES="20";
echo -e "\033[01;32m Iniciando Teste 1 a 18\033[1;37m"
sleep 1
echo ""

echo -e "\e[0m\e[01;37;41m TOKEN 1 - 5MB \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo

echo -e "\e[0m\e[01;37;41m TOKEN 2 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo

echo -e "\e[0m\e[01;37;41m TOKEN 3 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo

echo -e "\e[0m\e[01;37;41m TOKEN 4 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo

echo -e "\e[0m\e[01;37;41m TOKEN 5 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 6 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 7 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 8 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 9 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 10 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 11 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 12 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 13 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 14 100MB\e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 15 100MB\e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 16 100MB\e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 17 100MB\e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'
case $body in
null) echo -e "\e[01;33mReprovado"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "Erro"
esac
done
echo


echo -e "\e[0m\e[01;37;41m TOKEN 18 \e[0m"
for i in $(seq $VEZES);
do
response=$(data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl -s "${site}" -H "Referer: http://navegue.vivo.com.br/" -d "${data}")
body=$(echo $response | jq '.packprovision')
pack=$'"packprovisionOK"'

case $body in
null) echo -e "\e[01;33mReprovado - \e[0m \e[01;37mFinalizando...\e[0m"|pv -qL 20; break;;
$pack) echo -e "\e[01;32mAprovado\e[0m \e[01;37mTeste: $i\e[0m"|pv -qL 18;;
*) echo "ALGO DEU ERRADO"
esac
done
echo ""
echo -e "        \033[0m\033[01;37m• \033[01;32mTeste finalizado \033[01;37m•\033[0m"
sleep 2
